name: Hello World!

on: 
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps: 
      - name: Say Hello
        run: |
          echo "Hello World"

jobs:
  current_time_job:
    runs-on: ubuntu-20.04
    steps: 
      - name: Current time
        run: |
          echo date
          
jobs:
  current_directory_job:
    runs-on: ubuntu-20.04        
    steps: 
      - name: Current directory
        run: |
          echo ls -l